version: "3.3"

services:
  postgresql:
    image: arm64v8/postgres:13
    environment:
      - POSTGRES_PASSWORD=rootroot
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default: